/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.cliente;

import modelo.IBanco;

/**
 *
 * @author 44034660520
 */
public class Caixa extends javax.swing.JPanel {

    /**
     * Creates new form Caixa
     */
    IBanco banco;
    public Caixa(IBanco banco) {
        initComponents();
        this.banco=banco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboEscolha = new javax.swing.JComboBox();
        lblMensagem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Caixa eletrônico");
        add(jLabel1);
        jLabel1.setBounds(130, 10, 210, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Escolha sua opção:");
        add(jLabel2);
        jLabel2.setBounds(0, 70, 210, 40);

        comboEscolha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comboEscolha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha", "Depositar", "Retirar", "Extrato", "Trasferir" }));
        comboEscolha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEscolhaItemStateChanged(evt);
            }
        });
        add(comboEscolha);
        comboEscolha.setBounds(260, 80, 190, 30);

        lblMensagem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblMensagem);
        lblMensagem.setBounds(60, 160, 360, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void comboEscolhaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEscolhaItemStateChanged
        String texto = String.valueOf(comboEscolha.getSelectedItem());
        if(texto.equals("Depositar")){
            lblMensagem.setText("Depositar");
        }else{
            lblMensagem.setText("outro");
        }
    }//GEN-LAST:event_comboEscolhaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboEscolha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMensagem;
    // End of variables declaration//GEN-END:variables
}
