/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.cliente;

import gui.adm.*;
import javax.swing.JPanel;
import modelo.Agencia;
import modelo.Banco;
import modelo.Cliente;
import modelo.Conta;
import modelo.IBanco;

/**
 *
 * @author 44034660520
 */
public class Principal extends javax.swing.JFrame {

    IBanco banco;
    JPanel painelAtual;
    public Principal() {
        banco = new Banco();
        painelAtual = new Autenticacao(this,banco);
        this.painelAtual.setSize(500, 400);
        this.add(this.painelAtual);
        this.inicializarSistema();
        initComponents();
    }
    
    public void trocarPainel(JPanel painel){
        this.remove(this.painelAtual);
        this.painelAtual = painel;
        this.add(this.painelAtual);
        this.painelAtual.setSize(500, 400);
        this.painelAtual.setVisible(true);
    }

    private void inicializarSistema(){
        Agencia ag1=new Agencia("Raquel",256);
        Agencia ag2=new Agencia("Dimitrius",238);
        this.banco.adicionaAgencia(ag1);
        this.banco.adicionaAgencia(ag2);
        
        Cliente pedro=new Cliente("pedro Kislansky","123");
        Cliente sara=new Cliente("Sara Zilansky","111");
        
        Conta cta1 = new Conta(111,pedro);
        Conta cta2 = new Conta(222,sara);
        
        this.banco.adicionaConta(ag1, cta1);
        this.banco.adicionaConta(ag1, cta2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
