/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.adm;

import modelo.Agencia;
import modelo.IBanco;

/**
 *
 * @author 44034660520
 */
public class JPAgencia extends javax.swing.JPanel {

    IBanco banco;
    public JPAgencia(IBanco banco) {
        this.banco=banco;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGerente = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(500, 450));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("NOVA AGÊNCIA");
        jLabel1.setToolTipText("");
        add(jLabel1);
        jLabel1.setBounds(130, 20, 370, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Gerente");
        add(jLabel2);
        jLabel2.setBounds(70, 80, 80, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Número");
        add(jLabel3);
        jLabel3.setBounds(70, 140, 90, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Endereço");
        add(jLabel4);
        jLabel4.setBounds(70, 190, 100, 22);

        txtGerente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGerente.setToolTipText("");
        add(txtGerente);
        txtGerente.setBounds(190, 80, 250, 30);

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtNumero);
        txtNumero.setBounds(190, 130, 250, 30);

        txtEndereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        add(txtEndereco);
        txtEndereco.setBounds(190, 190, 250, 30);

        btAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        add(btAdicionar);
        btAdicionar.setBounds(310, 250, 130, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
       String gerente = txtGerente.getText();
       int numero = Integer.parseInt(txtNumero.getText());
       String end = txtEndereco.getText();
        Agencia ag = new Agencia(gerente,numero,end);
        this.banco.adicionaAgencia(ag);
        this.limparCampos();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void limparCampos(){
        txtGerente.setText("");
        txtNumero.setText("");
        txtEndereco.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtGerente;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
