/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.adm;

import javax.swing.JPanel;
import modelo.Banco;
import modelo.IBanco;

/**
 *
 * @author 44034660520
 */
public class Principal extends javax.swing.JFrame {

    IBanco banco;
    JPanel painelAtual;
    public Principal() {
        banco = new Banco();
        this.painelAtual=new JPanel();
        this.painelAtual.setSize(450, 450);
        this.add(this.painelAtual);
        initComponents();
    }
    
    private void trocarPainel(JPanel painel){
        this.remove(this.painelAtual);
        this.painelAtual = painel;
        this.add(this.painelAtual);
        this.painelAtual.setSize(500, 450);
        this.painelAtual.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        jmenuAgencia = new javax.swing.JMenuItem();
        jmenuConta = new javax.swing.JMenuItem();
        menuListagem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        menuCadastro.setText("Cadastro");

        jmenuAgencia.setText("Nova agência");
        jmenuAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuAgenciaActionPerformed(evt);
            }
        });
        menuCadastro.add(jmenuAgencia);

        jmenuConta.setText("Nova Conta");
        jmenuConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuContaActionPerformed(evt);
            }
        });
        menuCadastro.add(jmenuConta);

        jMenuBar1.add(menuCadastro);

        menuListagem.setText("Listagem");
        menuListagem.setActionCommand("Listagem");
        jMenuBar1.add(menuListagem);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuAgenciaActionPerformed
        JPanel agencia = new JPAgencia(this.banco);
        this.trocarPainel(agencia);
    }//GEN-LAST:event_jmenuAgenciaActionPerformed

    private void jmenuContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuContaActionPerformed
        JPanel conta = new JPConta(this.banco);
        this.trocarPainel(conta);
    }//GEN-LAST:event_jmenuContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmenuAgencia;
    private javax.swing.JMenuItem jmenuConta;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuListagem;
    // End of variables declaration//GEN-END:variables
}
